dbconf:
  driver: mysql
  hostname: 127.0.0.1
  hostport: 3306
  database: go_study
  username: root
  password: 111111
  prefix:
redisconf:
  hostname: 192.168.2.253
  hostport: 6379
  password: qttx123456
  db: 11
app:
  domain: 0.0.0.0
  env: dev #环境状态：dev=开发，pro=生产
  port: 8080
  version: 1.0.0
  requestlog : 1
